name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore & Build Solution
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build  FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ← no working-directory, defaults to repo root
      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      # frontend tests are skipped

  package:
    name: Package Artifacts
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: FlagExplorerAPI/bin/Release/net8.0/

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: build/
