name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build, Test & Package .NET Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

      - name: Publish Backend
        run: dotnet publish FlagExplorerAPI.sln --configuration Release --output publish

      - name: Upload Backend Package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: publish/**

  build-frontend:
    name: Build, Test & Package React Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run Frontend Tests
        run: npm test -- --ci --watchAll=false

      - name: Build Production Bundle
        run: npm run build

      - name: Package Frontend
        run: zip -r frontend.zip build/

      - name: Upload Frontend Package
        uses: actions/upload-artifact@v4
        with:
          name: frontend-package
          path: frontend.zip
