name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build Backend
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

  package:
    name: Zip & Archive Builds
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Prepare output folder
        run: mkdir -p output

      - name: Copy backend build
        run: |
          mkdir -p output/backend
          cp -r FlagExplorerAPI/bin/Release/net8.0/* output/backend/

      - name: Copy frontend build
        run: |
          mkdir -p output/frontend
          cp -r build/* output/frontend/

      - name: Zip all builds
        run: |
          cd output
          zip -r packaged-artifacts.zip backend frontend

      - name: Show zip contents
        run: unzip -l output/packaged-artifacts.zip || echo "Zipping failed"
