# .github/workflows/ci.yml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build and Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore and build
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run backend tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

      - name: Upload .NET API build
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: FlagExplorerAPI/bin/Release/net8.0/**

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      # To re-enable frontend tests, uncomment:
      # - name: Run frontend tests
      #   run: npm test -- --watchAll=false

      - name: Upload React build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build/**
