name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build

      # we're explicitly skipping `npm test` here
      # - name: Run frontend tests
      #   run: npm test -- --watchAll=false

  package:
    name: Package Artifacts
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v3

      - name: Debug .NET Output Path
        run: ls -l FlagExplorerAPI/bin/Release/net8.0/ || echo "Backend output folder missing"

      - name: Upload .NET API build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: FlagExplorerAPI/bin/Release/net8.0/

      - name: Debug React Output Path
        run: ls -l build/ || echo "Frontend build folder missing"

      - name: Upload React build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build/
