name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build API
        run: |
          dotnet restore FlagExplorerAPI.sln
          dotnet build   FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run API tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release

  build-frontend:
    name: Build React Frontend
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # run npm commands inside your `flag-explorer` folder:
      - name: Install dependencies
        working-directory: ./flag-explorer
        run: npm ci

      - name: Build production bundle
        working-directory: ./flag-explorer
        run: npm run build

  package:
    name: Package Artifacts
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Confirm your API output exists
      - name: Debug .NET output path
        run: |
          echo "👀 ls FlagExplorerAPI/bin/Release/net8.0"
          ls -R FlagExplorerAPI/bin/Release/net8.0 || echo "❌ API build folder missing!"

      - name: Upload .NET API build
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: FlagExplorerAPI/bin/Release/net8.0

      # Confirm your React output exists
      - name: Debug React output path
        run: |
          echo "👀 ls flag-explorer/build"
          ls -R flag-explorer/build || echo "❌ React build folder missing!"

      - name: Upload React build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: flag-explorer/build
