name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & build API
        run: |
          dotnet restore ./FlagExplorerAPI.sln
          dotnet build   ./FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run API tests
        run: dotnet test ./FlagExplorerAPI.sln --no-build --configuration Release

  build-frontend:
    name: Build React Frontend
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        # ← no `cd`, we’re already at the repo root where package.json lives

      - name: Build production bundle
        run: npm run build

      # If you ever want to re-enable frontend tests:
      # - name: Run frontend tests
      #   run: npm test -- --watchAll=false

  package:
    name: Package Artifacts
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug .NET output
        run: |
          echo "---- FlagExplorerAPI/bin/Release/net8.0 ----"
          ls -R FlagExplorerAPI/bin/Release/net8.0 || echo "❌ API folder missing!"

      - name: Upload .NET API build
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: FlagExplorerAPI/bin/Release/net8.0

      - name: Debug React output
        run: |
          echo "---- build/ ----"
          ls -R build || echo "❌ React build folder missing!"

      - name: Upload React build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: build
