name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore solution
        run: dotnet restore FlagExplorerAPI.sln

      - name: Build solution
        run: dotnet build FlagExplorerAPI.sln --no-restore --configuration Release

      - name: Run all tests
        run: dotnet test FlagExplorerAPI.sln --no-build --configuration Release
